name: CodSpeed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@2ac572851726409c88c02a307f1ea2632a9ea59b
        with:
          mode: simulation
          run: npx vitest bench --run
